# Generated by Django 3.1a1 on 2021-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Band', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='Established',
            field=models.DateField(null=True),
        ),
    ]
