# Generated by Django 3.1a1 on 2021-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
